version = "1"

[merge]
method = "squash"
automerge_label = "automerge"
require_automerge_label = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"

[update]
always = true

[approve]
auto_approve_usernames = []
